[package]
org = "wso2"
name = "tool_migrate_mirthchannel"
version = "0.1.0"
distribution = "2201.12.3"
keywords = ["migrate-mirthchannel", "mirthchannel-migrate", "mirthchannel", "mirthconnect", "mirth"]
